Server:
  RunMode: debug
  HttpPort: 8000
  WriteTimeout: 60
  ReadTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
DataBase:
  DBType: mysql
  Username: root
  Password:
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
